Documents/CollabProjTeam4-condor-master/src/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :issue_areas
  # link-up auth libraries
  devise_for :users

  scope format: false do
    resources :organizations, constraints: { id: /.+/ }
  end
  resources :opportunities

  # added ideas as a resource with all CRUD opertions
  # also added methods approve to allow admin users to approve/unapprove ideas
  resources :opportunities do
    put :favorite, on: :member
  end

  # routes the root directory to the homepage
  root 'welcome#welcome'
  get '/dashboard', to: 'organizations#dashboard', as: :dashboard_path
  get '/add_tags', to: 'users#show'
  put '/add_tags/add', to: 'users#add_tags', constraints: { sender: /[^\/]+/ }
end

Documents/CollabProjTeam4-condor-master/src/app/models/issue_area.rb
class IssueArea < ApplicationRecord
  validates_presence_of :name
end

Documents/CollabProjTeam4-condor-master/src/app/controllers/issue_areas_controller.rb
class IssueAreasController < ApplicationController
  before_action :set_issue_area, only: [:show, :edit, :update, :destroy]

  # GET /issue_areas
  # GET /issue_areas.json
  def index
    @issue_areas = IssueArea.all
  end

  # GET /issue_areas/1
  # GET /issue_areas/1.json
  def show
  end

  # GET /issue_areas/new
  def new
    @issue_area = IssueArea.new
  end

  # GET /issue_areas/1/edit
  def edit
  end

  # POST /issue_areas
  # POST /issue_areas.json
  def create
    @issue_area = IssueArea.new(issue_area_params)

    respond_to do |format|
      if @issue_area.save
        format.html { redirect_to @issue_area, notice: 'Issue area was successfully created.' }
        format.json { render :show, status: :created, location: @issue_area }
      else
        format.html { render :new }
        format.json { render json: @issue_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issue_areas/1
  # PATCH/PUT /issue_areas/1.json
  def update
    respond_to do |format|
      if @issue_area.update(issue_area_params)
        format.html { redirect_to @issue_area, notice: 'Issue area was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue_area }
      else
        format.html { render :edit }
        format.json { render json: @issue_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issue_areas/1
  # DELETE /issue_areas/1.json
  def destroy
    @issue_area.destroy
    respond_to do |format|
      format.html { redirect_to issue_areas_url, notice: 'Issue area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_issue_area
      @issue_area = IssueArea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_area_params
      params.require(:issue_area).permit(:name)
    end
end

Documents/CollabProjTeam4-condor-master/src/app/views/issue_areas/_form.html.erb
<%= form_with(model: issue_area, local: true) do |form| %>
  <% if issue_area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue_area.errors.count, "error") %> prohibited this issue_area from being saved:</h2>

      <ul>
      <% issue_area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Documents/CollabProjTeam4-condor-master/src/app/views/issue_areas/edit.html.erb
<h1>Editing Issue Area</h1>

<%= render 'form', issue_area: @issue_area %>

<%= link_to 'Show', @issue_area %> |
<%= link_to 'Back', issue_areas_path %>

Documents/CollabProjTeam4-condor-master/src/app/views/issue_areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issue Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issue_areas.each do |issue_area| %>
      <tr>
        <td><%= issue_area.name %></td>
        <td><%= link_to 'Show', issue_area %></td>
        <td><%= link_to 'Edit', edit_issue_area_path(issue_area) %></td>
        <td><%= link_to 'Destroy', issue_area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue Area', new_issue_area_path %>

Documents/CollabProjTeam4-condor-master/src/app/views/issue_areas/new.html.erb
<h1>New Issue Area</h1>

<%= render 'form', issue_area: @issue_area %>

<%= link_to 'Back', issue_areas_path %>

Documents/CollabProjTeam4-condor-master/src/app/views/issue_areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @issue_area.name %>
</p>

<%= link_to 'Edit', edit_issue_area_path(@issue_area) %> |
<%= link_to 'Back', issue_areas_path %>