src/config/routes.rb
Rails.application.routes.draw do

 resources :users, only: [:edit, :update]
 
 resources :posts do
  put :favorite, on: :member
end
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :issue_areas
  # link-up auth libraries
  devise_for :users

  scope format: false do
    resources :organizations, constraints: { id: /.+/ } do
        put :favorite, on: :member
    end
  end
  resources :opportunities

  # added ideas as a resource with all CRUD opertions
  # also added methods approve to allow admin users to approve/unapprove ideas
  resources :opportunities do
    put :favorite, on: :member
    put :signed_up, on: :member
  end

  # routes the root directory to the homepage
  root 'welcome#welcome'
  get '/dashboard', to: 'dashboards#index', as: :dashboard_path
 
  #get 'users/:id/edit', to: 'users#edit', as: :edit_user
  patch 'users/:id/edit', to: 'users#update'
  get '/add_tags', to: 'users#show'
  put '/add_tags/add', to: 'users#add_tags', constraints: { sender: /[^\/]+/ }
end

src/app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

src/app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

   #@user.user_img.attach(params[:user_img])

 def new
 end

=begin
 def img
     if !@user.img.attached? 
        @user.img.attach(params[:img])
    end
 end
=end

 def edit
 end
 
 def update
 end


def index
    if current_user.org?
      @organizations = Organization.where('email = ?', user_email)
      @organizations = @organizations.sort_by &:name
    
      @opportunities = Opportunity.where('email = ?', user_email)
      @opportunities = @opportunities.sort_by &:on_date
    elsif false # TODO ADMIN
      @organizations = Organization.all.sort_by &:name
    
      @opportunities = Opportunity.all.sort_by &:on_date
    else # normal user
      @organizations = Organization.where(approved: true).sort_by(&:name)
      @opportunities = Opportunity.all
      @favorites = current_user.favorited_opportunities
      @favorites = @favorites.sort_by(&:created_at).reverse
    end
end

end

src/app/helpers/dashboards_helper.rb
module DashboardsHelper
end

src/app/views/dashboards/index.html.erb
<% if current_user.org? %>
  <div class="opportunities">
    <h1>Your Organization status</h1>
    <div class="container">
      <% if current_user.unapproved_org? %>
        <p>
          You are <b>not</b> an approved organization.
          <br>
          Please contact CELR to have your organization certified and
          events be made visible to the public.

          If you did not mean to request for organization status, contact
          CELR and ask to decline it.
        </p>
      <% else %>
        <p>
          You are an approved organization. Your organization and events are visible to the public.
        </p>
      <% end %>
    </div>

  
  <!--THE PART I MOVED INTO THE LOOP-->


  <table>
    <h1>Pending Events</h1> #I add this part up
    
    
    <thead>
    <tr>
      <th style="white-space: nowrap;">Name</th>
      <th>Email</th>
      <th>City</th>
      <th>State</th>
      <th style="white-space: nowrap;">Zip Code</th>
      <th style="white-space: nowrap;">Issue Area</th>
      <th>Approved?</th>
      <th colspan="3"></th>
    </tr>
    </thead>
  
    <tbody>
    <% @organizations.each do |organization| %>
      <% if current_user.approved_org? %>
        <tr class="approved">
      <% else %>
        <tr class="unapproved">
      <% end %>
  
      <td><%= organization.name %></td>
      <td><%= organization.email %></td>
      <td><%= organization.city %></td>
      <td><%= organization.state %></td>
      <td><%= organization.zip_code %></td>
      <td><%= organization.issue_area %></td>
      <% if current_user.approved_org? %>
        <td>Yes</td>
      <% else %>
        <td>No</td>
      <% end %>
  
      <td><%= link_to 'View', organization %></td>
      <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
      <td><%= link_to 'Delete', organization, method: :delete, data: {confirm: 'Are you sure?'} %></td>
  
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% end %>


<div class="opportunities">
  <% if current_user.org? %>
    <h1>Your Events</h1>

    <table>
      <thead>
      <tr>
        <th style="white-space: nowrap;">Event Name</th>
        <th>Organization</th>
        <th>City</th>
        <th>State</th>
        <th>Date</th>
        <th style="white-space: nowrap;">Issue Area</th>
        <th>Visible?</th>
        <th colspan="2"></th>
        <th style="white-space: nowrap;">
          <div class="styledButton">
            <%= link_to 'New', new_opportunity_path %>
          </div>
        </th>
      </tr>
      </thead>

      <tbody>
      <% @opportunities.each do |opportunity| %>
        <% if opportunity.approved? %>
          <tr class="approved">
        <% else %>
          <tr class="unapproved">
        <% end %>

        <td><%= opportunity.name %></td>
        <td><%= opportunity.organization.name %></td>
        <td><%= opportunity.city %></td>
        <td><%= opportunity.state %></td>
        <% if opportunity.on_date >= Date.current %>
          <td style="white-space: nowrap;"><%= opportunity.on_date.strftime('%B %-d, %Y') %></td>
        <% else %>
          <td style="white-space: nowrap; color: red;"><%= opportunity.on_date.strftime('%B %-d, %Y') %></td>
        <% end %>
        <td><%= opportunity.issue_area %></td>
        <% if opportunity.approved? && opportunity.on_date >= Date.current %>
          <td>Yes</td>
        <% else %>
          <td>No</td>
        <% end %>

        <td><%= link_to 'View', opportunity %></td>
        <td><%= link_to 'Edit', edit_opportunity_path(opportunity) %></td>
        <td><%= link_to 'Delete', opportunity, method: :delete, data: {confirm: 'Are you sure?'} %></td>

        </tr>


      <% end %>
      </tbody>

    </table>

    </div>
    <br>
    <p class="container">Note: All expired events (with dates shown in <span style="color: red;">red</span>)
      will not be visible to the public, even if approved.</p>
  <% else %>
  
  <!--My_Profile page starts here - User view-->
      <% if user_signed_in?  %>
      <div class = "my_profile_left">
        
            <h1>My Profile</h1>
            <!-- Profile Picture Goes Here
        <nav style = "text-align: center;">
            <img source = "src/app/assets/images/Profile_Default.jpg" alt = "Default_Profile_Pic" width="240" height="240">
        </nav>
        -->
                
        <br>
        <!--
        
        <form style="text-align: center; width:100%; padding:2rem 0rem 0rem; " action="myform.cgi">
                <input type="file" name="fileupload" accept="image/*" >
                
        Check 191 here : https://stackoverflow.com/questions/572768/styling-an-input-type-file-button
                <%= link_to 'Upload' %>
        </form>
        
        -->
        <form style= "text-align:center;" action='posts' method="POST" enctype="multipart/form-data">
          <div id="yourBtn" style=" height: 240px; width: 240px; margin:0 auto; border: 1px dashed #BBB; cursor:pointer;">
            <nav style = "padding: 40% 0 0 0;">Click to upload!</nav>
            
             <!-- 
            #if @user.img 
            <image style = "text-align: center; border: 1px solid black" src ="##(url_for(@user.img))" alt = "Default_Profile_Pic" width="240" height="240">
             #else 
             #end  -->
            
            
          </div>
          <br>
          <div class="styledButton">
              <%= link_to 'Upload' %>
          </div>
          
          <!-- this is your file input tag, so i hide it!>
          
          <div style='height: 0px;width:0px; overflow:hidden;'><input id="upfile" type="file" value="upload"/></div>
          <input type="submit" value='Upload' >
          
            <here you can have file submit button or you can write a simple script to upload the file automatically-->
        </form>

        <nav style="text-align: center;">
           <br><td><%= "Email: " + current_user.email %></td>
           <br><td><%= "Name: " + current_user.name %></td>
           <br><td><%= "Address: " + current_user.address %></td>
           <br><td><%= "ID Number:" %></td>
        </nav>
        
    
        <div style ="text-align:center; padding: 5% 0 5% 0">
          <div class="styledButton">
            <% if false %>
            <%=link_to 'Edit Profile', edit_profile_path_url %>
            <% end %>
            <%=link_to 'Edit', edit_user_path(current_user)%>
          </div> 
        </div>
        
        <br>
         
      </div>
      <% end %>
      
      
      <div class = "my_profile_right">
        <h1>Events Attending</h1>
  
        <table>
          <thead>
          <tr>
            <th style="white-space: nowrap;">Event Name</th>
            <th>Organization</th>
            <th>City</th>
            <th>State</th>
            <th>Date</th>
            <th style="white-space: nowrap;">Issue Area</th>
            <th colspan="3"></th>
  
          </tr>
          </thead>
  
          <tbody>
          <% current_user.signed_up.each do |event| %>
             <%  @opportunity = Opportunity.find(event) %>
              <tr>
              <td><%= @opportunity.name %></td>
              <td><%= @opportunity.organization.name %></td>
              <td><%= @opportunity.city %></td>
              <td><%= @opportunity.state %></td>
              <td><%= @opportunity.on_date %></td>
              <td><%= @opportunity.issue_area %></td>
              </tr>
          <% end %>
          
          </table>
        
        
        <br><br>
        <h1>Favorite Organizations</h1>
  
        <table>
          <thead>
          <tr>
            <th style="white-space: nowrap;">Organization</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Email</th>
            <th style="white-space: nowrap;">Issue Area</th>
            <th colspan="3"></th>
  
          </tr>
          </thead>
  
          <tbody>
          <% current_user.fav_org.each do |favorite| %>
             <%  @organization = Organization.find(favorite) %>
              <tr>
              <td><%= @organization.name %></td>
              <td><%= @organization.address %></td>
              <td><%= @organization.city %></td>
              <td><%= @organization.state %></td>
              <td><%= @organization.email %></td>
              <td><%= @organization.issue_area %></td>
              </tr>
          <% end %>
          </table>
          
          
          <br>
          <br>
          <h1>Favorite Events</h1>
  
        <table>
          <thead>
          <tr>
            <th style="white-space: nowrap;">Event Name</th>
            <th>Organization</th>
            <th>City</th>
            <th>State</th>
            <th>Date</th>
            <th style="white-space: nowrap;">Issue Area</th>
            <th colspan="3"></th>
  
          </tr>
          </thead>
  
          <tbody>
          <% current_user.fav_event.each do |favorite| %>
             <%  @opportunity = Opportunity.find(favorite) %>
              <tr>
              <td><%= @opportunity.name %></td>
              <td><%= @opportunity.organization.name %></td>
              <td><%= @opportunity.city %></td>
              <td><%= @opportunity.state %></td>
              <td style="white-space: nowrap;"><%= @opportunity.on_date.strftime('%B %-d, %Y') %></td>
              <td><%= @opportunity.issue_area %></td>
              </tr>
          <% end %>
          </tbody>
  
        </table>
 

 </div>
   

  <% end %>