src/config/routes.rb
Rails.application.routes.draw do

 resources :users, only: [:edit, :update]
 
 resources :posts do
  put :favorite, on: :member
end
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :issue_areas
  # link-up auth libraries
  devise_for :users

  scope format: false do
    resources :organizations, constraints: { id: /.+/ } do
        put :favorite, on: :member
    end
  end
  resources :opportunities

  # added ideas as a resource with all CRUD opertions
  # also added methods approve to allow admin users to approve/unapprove ideas
  resources :opportunities do
    put :favorite, on: :member
    put :signed_up, on: :member
  end

  # routes the root directory to the homepage
  root 'welcome#welcome'
  get '/dashboard', to: 'dashboards#index', as: :dashboard_path
 
  #get 'users/:id/edit', to: 'users#edit', as: :edit_user
  patch 'users/:id/edit', to: 'users#update'
  get '/add_tags', to: 'users#show'
  put '/add_tags/add', to: 'users#add_tags', constraints: { sender: /[^\/]+/ }
end

src/app/controllers/organizations_controller.rb
# frozen_string_literal: true

# Idea Project
# This gives the user and orgs the ability to create ideas to:
# help the community and allow for collaboration
#
# organizations_controller.rb

# Filename: organizations_controller.rb
# Description: this file is the controller class for the organization view page and all associated
# interactions
class OrganizationsController < ApplicationController
  
  
  before_action :set_organization, only: %i[show edit update destroy]

  # GET /organizations
  # GET /organizations.json
  # Function: index
  # Parameters: none
  # Pre-Condition: the user selects the organizations view from the toolbar
  # Post-Condition: a table of all organizations will be displayed to the user
  def index
    @organizations = Organization.all
    @organizations = @organizations.sort_by &:name
    @name = current_user
  end

  # GET /organizations/1
  # GET /organizations/1.json
  # Function: show
  # Parameters: none
  # Pre-Condition: the user selects view for some organization in the view
  # Post-Condition: a page with all of the organizataions information will be displayed
  def show
    @name = current_user  
    @organization = Organization.find(params[:id])
  end

  # Function: dashboard
  # Parameters: none
  # Pre-Condition: the user selects the organization/user dashboard view from the toolbar
  # Post-Condition: the user will be displayed all of the
  def dashboard
    if current_user.org?
      @organizations = Organization.where('email = ?', user_email)
      @organizations = @organizations.sort_by &:name

      @opportunities = Opportunity.where('email = ?', user_email)
      @opportunities = @opportunities.sort_by &:on_date
    elsif false # TODO ADMIN
      @organizations = Organization.all.sort_by &:name

      @opportunities = Opportunity.all.sort_by &:on_date
    else # normal user
      @organizations = Organization.where(approved: true).sort_by(&:name)
      @opportunities = Opportunity.all
      @favorites = current_user.favorited_opportunities
      @favorites = @favorites.sort_by(&:created_at).reverse
    end
  end

  # GET /organizations/new
  # Function: new
  # Parameters: none
  # Pre-Condition: the user attempts to create a new organization account
  # Post-Condition: the form for the organization information will be displayed to be filled out
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  # Function: edit
  # Parameters: none
  # Pre-Condition: the user selects the edit button next to their organization
  # Post-Condition: the user will be displayed the edit page to make changes
  def edit; end

  # POST /organizations
  # POST /organizations.json
  # Function: create
  # Parameters: none
  # Pre-Condition: the user must have filled out the org form and then click the create button
  # Post-Condition: the organizations information will be  in the table to the new information
  def create
    p = organization_params
    p[:email] = user_email
    @organization = Organization.new(p)
    @organization.approved = FALSE
    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end


  def favorite
    @organization = Organization.find(params[:id])
    if current_user.fav_org.empty? or !current_user.fav_org.include? @organization.id.to_s
      temp = current_user.fav_org << @organization.id
    else
      temp = current_user.fav_org - [@organization.id.to_s]
    end
      current_user.update_attribute(:fav_org, temp)
    redirect_back fallback_location: favorite_organization_path
  end


  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  # Function: update
  # Parameters: none
  # Pre-Condition: the user must have made some changes to the edit form and hit the update button
  # Post-Condition: the organizations information will be updated in the table
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  # Function: destroy
  # Parameters: none
  # Post-Condition: the organization will be removed from the table
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Organization.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:email, :name, :phone_no, :address, :city, :state, :zip_code, :description, :approved, :issue_area)
  end

  def edit_profile
    if current_user.org?
      @organizations = Organization.where('email = ?', user_email)
      @organizations = @organizations.sort_by &:name

      @opportunities = Opportunity.where('email = ?', user_email)
      @opportunities = @opportunities.sort_by &:on_date
    elsif false # TODO ADMIN
      @organizations = Organization.all.sort_by &:name

      @opportunities = Opportunity.all.sort_by &:on_date
    else # normal user
      @organizations = Organization.where(approved: true).sort_by(&:name)
      @opportunities = Opportunity.all
      @favorites = current_user.favorited_opportunities
      @favorites = @favorites.sort_by(&:created_at).reverse 
    end
  end
  
  
end

src/app/views/organizations/dashboard.html.erb
<% if current_user.org? %>
  <div class="opportunities">
    <h1>Your Organization status</h1>
    <div class="container">
      <% if current_user.unapproved_org? %>
        <p>
          You are <b>not</b> an approved organization.
          <br>
          Please contact CELR to have your organization certified and
          events be made visible to the public.

          If you did not mean to request for organization status, contact
          CELR and ask to decline it.
        </p>
      <% else %>
        <p>
          You are an approved organization. Your organization and events are visible to the public.
        </p>
      <% end %>
    </div>

  
  <!--THE PART I MOVED INTO THE LOOP-->


  <table>
    <h1>Pending Events</h1> #I add this part up
    
    
    <thead>
    <tr>
      <th style="white-space: nowrap;">Name</th>
      <th>Email</th>
      <th>City</th>
      <th>State</th>
      <th style="white-space: nowrap;">Zip Code</th>
      <th style="white-space: nowrap;">Issue Area</th>
      <th>Approved?</th>
      <th colspan="3"></th>
    </tr>
    </thead>
  
    <tbody>
    <% @organizations.each do |organization| %>
      <% if current_user.approved_org? %>
        <tr class="approved">
      <% else %>
        <tr class="unapproved">
      <% end %>
  
      <td><%= organization.name %></td>
      <td><%= organization.email %></td>
      <td><%= organization.city %></td>
      <td><%= organization.state %></td>
      <td><%= organization.zip_code %></td>
      <td><%= organization.issue_area %></td>
      <% if current_user.approved_org? %>
        <td>Yes</td>
      <% else %>
        <td>No</td>
      <% end %>
  
      <td><%= link_to 'View', organization %></td>
      <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
      <td><%= link_to 'Delete', organization, method: :delete, data: {confirm: 'Are you sure?'} %></td>
  
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% end %>


<div class="opportunities">
  <% if current_user.org? %>
    <h1>Your Events</h1>

    <table>
      <thead>
      <tr>
        <th style="white-space: nowrap;">Event Name</th>
        <th>Organization</th>
        <th>City</th>
        <th>State</th>
        <th>Date</th>
        <th style="white-space: nowrap;">Issue Area</th>
        <th>Visible?</th>
        <th colspan="2"></th>
        <th style="white-space: nowrap;">
          <div class="styledButton">
            <%= link_to 'New', new_opportunity_path %>
          </div>
        </th>
      </tr>
      </thead>

      <tbody>
      <% @opportunities.each do |opportunity| %>
        <% if opportunity.approved? %>
          <tr class="approved">
        <% else %>
          <tr class="unapproved">
        <% end %>

        <td><%= opportunity.name %></td>
        <td><%= opportunity.organization.name %></td>
        <td><%= opportunity.city %></td>
        <td><%= opportunity.state %></td>
        <% if opportunity.on_date >= Date.current %>
          <td style="white-space: nowrap;"><%= opportunity.on_date.strftime('%B %-d, %Y') %></td>
        <% else %>
          <td style="white-space: nowrap; color: red;"><%= opportunity.on_date.strftime('%B %-d, %Y') %></td>
        <% end %>
        <td><%= opportunity.issue_area %></td>
        <% if opportunity.approved? && opportunity.on_date >= Date.current %>
          <td>Yes</td>
        <% else %>
          <td>No</td>
        <% end %>

        <td><%= link_to 'View', opportunity %></td>
        <td><%= link_to 'Edit', edit_opportunity_path(opportunity) %></td>
        <td><%= link_to 'Delete', opportunity, method: :delete, data: {confirm: 'Are you sure?'} %></td>

        </tr>


      <% end %>
      </tbody>

    </table>

    </div>
    <br>
    <p class="container">Note: All expired events (with dates shown in <span style="color: red;">red</span>)
      will not be visible to the public, even if approved.</p>
  <% else %>
  
  <!--My_Profile page starts here - User view-->
      <% if user_signed_in?  %>
      <div class = "my_profile_left">
        
            <h1>My Profile</h1>
            <!-- Profile Picture Goes Here
        <nav style = "text-align: center;">
            <img source = "src/app/assets/images/Profile_Default.jpg" alt = "Default_Profile_Pic" width="240" height="240">
        </nav>
        -->
                
        <br>
        <!--
        
        <form style="text-align: center; width:100%; padding:2rem 0rem 0rem; " action="myform.cgi">
                <input type="file" name="fileupload" accept="image/*" >
                
        Check 191 here : https://stackoverflow.com/questions/572768/styling-an-input-type-file-button
                <%= link_to 'Upload' %>
        </form>
        
        -->
        <form style= "text-align:center;" action="#type your action here" method="POST" enctype="multipart/form-data">
          <div id="yourBtn" style=" height: 240px; width: 240px; margin:0 auto; border: 1px dashed #BBB; cursor:pointer;" onclick="getFile()">
            <nav style = "padding: 40% 0 0 0;">Click to upload!</nav>
          </div>
          <br>
          <div class="styledButton">
              <%= link_to 'Upload' %>
          </div>
          
          <!-- this is your file input tag, so i hide it!>
          
          <div style='height: 0px;width:0px; overflow:hidden;'><input id="upfile" type="file" value="upload"/></div>
          <input type="submit" value='Upload' >
          
            <here you can have file submit button or you can write a simple script to upload the file automatically-->
        </form>

        <nav style="text-align: center;">
           <br><td><%= "Email: " + current_user.email %></td>
           <br><td><%= "Name: " + current_user.name %></td>
           <br><td><%= "Address: " + current_user.address %></td>
           <br><td><%= "ID Number: #########"%></td>
        </nav>
        
        <div style ="text-align:center; padding: 5% 0 5% 0">
          <div class="styledButton">
            <%= link_to 'Edit Profile', edit_profile_path_url %>
          </div> 
        </div>
        
        <br>
         
      </div>
      <% end %>
      
      
      <div class = "my_profile_right">
        <h1>Favorite Organizations</h1>
  
        <table>
          <thead>
          <tr>
            <th style="white-space: nowrap;">Event Name</th>
            <th>Organization</th>
            <th>City</th>
            <th>State</th>
            <th>Date</th>
            <th style="white-space: nowrap;">Issue Area</th>
            <th colspan="3"></th>
  
          </tr>
          </thead>
  
          <tbody>
          <% @favorites.each do |favorite| %>
  
            <tr>
              <% opportunity = favorite %>
  
              <td><%= opportunity.name %></td>
              <td><%= opportunity.organization.name %></td>
              <td><%= opportunity.city %></td>
              <td><%= opportunity.state %></td>
              <td style="white-space: nowrap;"><%= opportunity.on_date.strftime('%B %-d, %Y') %></td>
              <td><%= opportunity.issue_area %></td>
  
              <td><%= link_to 'View', opportunity %></td>
  <!--            FIXME: correct link-->
              <td>Unfavorite (in repair)<%#= link_to 'Unfavorite', favorite_opportunity_path(@opportunity, :id => opportunity.id, type: "unfavorite"), method: :put %></td>
  
            </tr>
  
  
          <% end %>
          </table>
          <br>
          <br>
          <h1>Favorite Events</h1>
  
        <table>
          <thead>
          <tr>
            <th style="white-space: nowrap;">Event Name</th>
            <th>Organization</th>
            <th>City</th>
            <th>State</th>
            <th>Date</th>
            <th style="white-space: nowrap;">Issue Area</th>
            <th colspan="3"></th>
  
          </tr>
          </thead>
  
          <tbody>
          <% @favorites.each do |favorite| %>
  
            <tr>
              <% opportunity = favorite %>
  
              <td><%= opportunity.name %></td>
              <td><%= opportunity.organization.name %></td>
              <td><%= opportunity.city %></td>
              <td><%= opportunity.state %></td>
              <td style="white-space: nowrap;"><%= opportunity.on_date.strftime('%B %-d, %Y') %></td>
              <td><%= opportunity.issue_area %></td>
  
              <td><%= link_to 'View', opportunity %></td>
  <!--            FIXME: correct link-->
              <td>Unfavorite (in repair)<%#= link_to 'Unfavorite', favorite_opportunity_path(@opportunity, :id => opportunity.id, type: "unfavorite"), method: :put %></td>
  
            </tr>
  
  
          <% end %>
          </tbody>
  
        </table>
 

 </div>
   

  <% end %>

src/app/views/organizations/edit_profile.html.erb
<% if current_user.org? %>
  <div class="opportunities">
    <h1>Your Organization status</h1>
    <div class="container">
      <% if current_user.unapproved_org? %>
        <p>
          You are <b>not</b> an approved organization.
          <br>
          Please contact CELR to have your organization certified and
          events be made visible to the public.

          If you did not mean to request for organization status, contact
          CELR and ask to decline it.
        </p>
      <% else %>
        <p>
          You are an approved organization. Your organization and events are visible to the public.
        </p>
      <% end %>
    </div>

  
  <!--THE PART I MOVED INTO THE LOOP-->


  <table>
    <h1>Pending Events</h1> #I add this part up
    
    
    <thead>
    <tr>
      <th style="white-space: nowrap;">Name</th>
      <th>Email</th>
      <th>City</th>
      <th>State</th>
      <th style="white-space: nowrap;">Zip Code</th>
      <th style="white-space: nowrap;">Issue Area</th>
      <th>Approved?</th>
      <th colspan="3"></th>
    </tr>
    </thead>
  
    <tbody>
    <% @organizations.each do |organization| %>
      <% if current_user.approved_org? %>
        <tr class="approved">
      <% else %>
        <tr class="unapproved">
      <% end %>
  
      <td><%= organization.name %></td>
      <td><%= organization.email %></td>
      <td><%= organization.city %></td>
      <td><%= organization.state %></td>
      <td><%= organization.zip_code %></td>
      <td><%= organization.issue_area %></td>
      <% if current_user.approved_org? %>
        <td>Yes</td>
      <% else %>
        <td>No</td>
      <% end %>
  
      <td><%= link_to 'View', organization %></td>
      <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
      <td><%= link_to 'Delete', organization, method: :delete, data: {confirm: 'Are you sure?'} %></td>
  
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% end %>


<div class="opportunities">
  <% if current_user.org? %>
    <h1>Your Events</h1>

    <table>
      <thead>
      <tr>
        <th style="white-space: nowrap;">Event Name</th>
        <th>Organization</th>
        <th>City</th>
        <th>State</th>
        <th>Date</th>
        <th style="white-space: nowrap;">Issue Area</th>
        <th>Visible?</th>
        <th colspan="2"></th>
        <th style="white-space: nowrap;">
          <div class="styledButton">
            <%= link_to 'New', new_opportunity_path %>
          </div>
        </th>
      </tr>
      </thead>

      <tbody>
      <% @opportunities.each do |opportunity| %>
        <% if opportunity.approved? %>
          <tr class="approved">
        <% else %>
          <tr class="unapproved">
        <% end %>

        <td><%= opportunity.name %></td>
        <td><%= opportunity.organization.name %></td>
        <td><%= opportunity.city %></td>
        <td><%= opportunity.state %></td>
        <% if opportunity.on_date >= Date.current %>
          <td style="white-space: nowrap;"><%= opportunity.on_date.strftime('%B %-d, %Y') %></td>
        <% else %>
          <td style="white-space: nowrap; color: red;"><%= opportunity.on_date.strftime('%B %-d, %Y') %></td>
        <% end %>
        <td><%= opportunity.issue_area %></td>
        <% if opportunity.approved? && opportunity.on_date >= Date.current %>
          <td>Yes</td>
        <% else %>
          <td>No</td>
        <% end %>

        <td><%= link_to 'View', opportunity %></td>
        <td><%= link_to 'Edit', edit_opportunity_path(opportunity) %></td>
        <td><%= link_to 'Delete', opportunity, method: :delete, data: {confirm: 'Are you sure?'} %></td>

        </tr>


      <% end %>
      </tbody>

    </table>

    </div>
    <br>
    <p class="container">Note: All expired events (with dates shown in <span style="color: red;">red</span>)
      will not be visible to the public, even if approved.</p>
  <% else %>
  
  <!--My_Profile page starts here - User view-->
      <% if user_signed_in?  %>
        <div class = "opportunities">
          <div class = "edit_my_profile">
          
            <h1>My Profile</h1>
            <!-- Profile Picture Goes Here
              <nav style = "text-align: center;">
              <img source = "src/app/assets/images/Profile_Default.jpg" alt = "Default_Profile_Pic" width="240" height="240">
              </nav>
              -->
                  
            <br>
            <!--
            
            <form style="text-align: center; width:100%; padding:2rem 0rem 0rem; " action="myform.cgi">
                    <input type="file" name="fileupload" accept="image/*" >
                    
            Check 191 here : https://stackoverflow.com/questions/572768/styling-an-input-type-file-button
                    <%= link_to 'Upload' %>
            </form>
            
            -->
            <form action="#type your action here" method="POST" enctype="multipart/form-data">
              <div id="yourBtn" style=" height: 240px; width: 240px; margin:0 auto; border: 1px dashed #BBB; cursor:pointer;" onclick="getFile()">
                <nav style = "padding: 40% 0 0 0;">Click to upload!</nav>
              </div>
              
              <br>
              
              <div class="edit_my_profile_button">
                  <%= link_to 'Upload' %>
              </div>
              
              <!-- this is your file input tag, so i hide it!>
              
              <div style='height: 0px;width:0px; overflow:hidden;'><input id="upfile" type="file" value="upload"/></div>
              <input type="submit" value='Upload' >
              
                <here you can have file submit button or you can write a simple script to upload the file automatically-->
            </form>
  
            <div class = "edit_box">
               <br><td><%= "Email: " + current_user.email %></td>
               <br>
               
    		      <%= form_for :user do |f| %>
                <%= f.text_field :name %>
                  <%= f.submit %>
              <% end %>

    		      
               <br><td><%= "ID Number: #########"%></td>
               
            </div>
        
          <br>
        	<div class="styledButton">
        	  
              <%= link_to 'Save Changes', dashboard_path_url %>
          </div>
        </div>
      </div>
      <% end %> 

  <% end %>

src/app/views/organizations/show.html.erb
<html>
  <% if (@name.fav_org.include? @organization.id.to_s) %>
       <% temp = "Unfavorite"%>
    <% else %>
      <% temp = "Favorite"%>
    <% end %>  
    <div style = "text-align: center">
      <div class="styledButton">
        <%= link_to temp, favorite_organization_path, method: :put %>
      </div>
    </div>
<table>
  <thead>
  <tr>
    <th>Name: <%= @organization.name %></th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><strong>Email:</strong>
      <%= @organization.email %></td>
    <td><strong>Phone no:</strong>
      <%= @organization.phone_no %></td>
  </tr>
  <tr>
    <td class="location-tab"><strong>Address:</strong>
      <%= @organization.address %></td>
    <td class="location-tab">
      <strong>City:</strong>
      <%= @organization.city %>
    </td>
  </tr>

  <tr>
    <td>
      <strong>State:</strong>
      <%= @organization.state %>
    </td>
    <td>
      <strong>Zip code:</strong>
      <%= @organization.zip_code %>
    </td>
  </tr>

  <tr>
    <td colspan="3">
      <strong>Description:</strong>
      <%= @organization.description %>
    </td>

  </tr>

  <tr>
    <td colspan="3">
      <strong>Issue Area:</strong>
      <%= @organization.issue_area %>
    </td>

  </tr>

  <tr>
    <td colspan="3">
      <strong>Approved:</strong>
      <%= @organization.approved %>
    </td>

  </tr>
  </tbody>
</table>

<br><br>
<div style="text-align: center;">
  <div style="display: inline-block; text-align: left;">
    <div class="styledButton">
      <% if session[:user_email] == @organization.email || session[:user_type] == 0 %>
        <%= link_to 'Edit', edit_organization_path(@organization) %> |
      <% end %>
    </div>

    <div class="styledButton">
      <%= link_to 'Back', :back %>
    </div>
  </div>
</div>
</html>